import 'dart:async';
import 'package:client/config/routes/routes_constants.dart';
import 'package:client/features/app/presentation/bloc/app_bloc.dart';
import 'package:client/features/auth/presentation/pages/login_page.dart';
import 'package:client/features/home/presentation/pages/authenticated_home_page.dart';
import 'package:client/features/home/presentation/pages/guest_home_page.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
part 'app_route.main.dart';
